<!doctype html>
<html lang="es" ng-app="musicien">
  <head>
    <title>MUSICIEN - Bringing Music Back to Live</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->


    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css" />

    <link href="css/custom.css" rel="stylesheet">
    <link href="css/loaders.css" rel="stylesheet">
    <link href="css/swiper.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/component.css">
    <link rel="stylesheet" href="css/demo.css">
    <link rel="stylesheet" href="css/ionicons.min.css" />
    <link rel="stylesheet" href="css/font-awesome.min.css" />
    <link  rel="stylesheet" href="css/emoji.css">
    <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css" type="text/css"/>


    <!--Google Font-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700,700i" rel="stylesheet">
    <!--Favicon-->
    <link rel="shortcut icon" type="image/png" href="images/fav.png"/>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.8.5/css/selectize.default.css">
    <link rel="stylesheet" href="css/style.css" />
    <link rel="stylesheet" href="css/ionicons.min.css" />
    <link rel="stylesheet" href="css/font-awesome.min.css" />
    <link  rel="stylesheet" href="css/emoji.css">
    <link rel="stylesheet" href="css/selec.css">
    <link rel="stylesheet" href="css/slider-wrapper.css">

    <!-- <script src="http://platform.twitter.com/widgets.js"></script> -->
    <!--Google Font-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700,700i" rel="stylesheet">
    <!--Favicon-->
    <link rel="shortcut icon" type="image/png" href="images/fav.png"/>
    <!--   ANGULAR 1.6 -->
    <!--<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <script type="text/javascript" src="https://code.angularjs.org/1.3.15/angular-route.min.js">-->
   <!--  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js"></script> -->
    <!--<script type="text/javascript" src="js/angular.js">

    </script>-->
   <!--  <script type="text/javascript" src="js/angular-route.min.js">

    </script> -->
    <!--<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js"></script>-->
    <!-- <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-animate.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-sanitize.js"></script>
    <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.js"></script> -->

    <!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <!--<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-animate.js"></script>-->
    <!--<script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.14.3.js"></script>-->


    <!--Angular Extensiones -->
    <!--<script type="text/javascript" src="js/angular-route.js">

    </script>-->
   <!--   <script src="js/jquery.sticky-kit.min.js"></script> -->
    <script src="http://82.223.27.144/dsSignalRChat/Scripts/jquery.signalR-2.2.2.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
   <!--  <script src="hubssignalr"></script>
    <script type="text/javascript" src="apps/funciones.js">

    </script>
    <script type="text/javascript" src="js/infinite-scroll.js">

    </script> -->

    <!--Angular App-->
   <!--  <script type="text/javascript" src="apps/app.js">

    </script>
    <script type="text/javascript" src="apps/routeProvider.js">

    </script>
    <script type="text/javascript" src="apps/configuracionGlobal.js">

    </script>
    <script type="text/javascript" src="apps/directivas.js">

    </script>
    <script type="text/javascript" src="controllers/carritoCompraController.js">

    </script>
    <script type="text/javascript" src="apps/llamadashttp.js">

    </script>
    <script type="text/javascript" src="controllers/crearpostController.js">

    </script> -->
    <!--Angular Controladores -->
    <!-- <script type="text/javascript" src="controllers/navegacionController.js">

    </script>
    <script type="text/javascript" src="controllers/inicioController.js">

    </script>
    <script type="text/javascript" src="controllers/preferenciasController.js">

    </script>
    <script type="text/javascript" src="controllers/previsualizadorController.js">

    </script>
    <script src="controllers/ui-angularController.js">
    </script>
    <script type="text/javascript" src="controllers/valorarpublicacionController.js">

    </script>
    <script type="text/javascript" src="controllers/publicacionController.js">

    </script>
    <script type="text/javascript" src="controllers/registrologinController.js">

    </script>
    <script type="text/javascript" src="controllers/redesSociales.js">

    </script>
    <script type="text/javascript" src="controllers/perfilusuarioController.js">

    </script>
     <script type="text/javascript" src="apps/chatProvider.js">

    </script>
    <script type="text/javascript" src="controllers/notificacionesController.js">

    </script>
    <script type="text/javascript" src="js/selec.js">
    </script> -->
    <!-- <script type="text/javascript" src="js/jquery.scrollbar.js"></script>
    <script src="js/sticky.js"></script>
    <script src="js/angular-slide-wrapper.js"></script>
    <script src="js/anchor-scroll.js" type="text/javascript"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="js/scrollbars.min.js"></script>
       <script type="text/javascript" src="js/spotify-web-api.js">

    </script> -->

    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '290207971502502',
          cookie     : true,
          xfbml      : true,
          version    : 'v2.10'
        });

        FB.AppEvents.logPageView();

      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script type="text/javascript">
      var OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
        OneSignal.init({
          appId: "a34da277-1dc3-4273-8316-09c6c7435e0a",
          autoRegister: false,
          notifyButton: {
            enable: false,
          },
        });
      });

    </script>
    <script type="text/javascript">
    OneSignal.push(function() {
      // Occurs when the user's subscription changes to a new value.
      OneSignal.on('subscriptionChange', function (isSubscribed) {
        console.log("The user's subscription state is now:", isSubscribed);
        cambioSuscripcion(isSubscribed);
      });
    });
  </script>
    <script type="text/javascript" src="apps/notifyProvider.js">

    </script>

  </head>
  <body  style="text-align:center">
<!-- <div id="loaderraro" class="loader loader-bg" onclick="eliminarLoader()"> -->

    <div></div>
    <div></div>
  </div>
</div>
    <!-- INICIO HEADER -->
  <header id="header" class="">
    <div class="container ">
     <nav class="navbar navbar-expand-lg fixed-top menu ">
      <div class="container" >
        <a class="navbar-brand" ng-click="inicio()">
            <img src="img/logo_p.png" class="m-0 p-0" height="30"> <span class="ml-1">MUSICIEN</span>
        </a>



      </div>

     </nav>
      <div class="row">
          <div class="col-6 offset-3">

          </div>
        </div>

    </div>
      </header>
<!-- FIN HEADER -->





  <?php
                if (true) {
                  $id = $_GET['Id'];
                  $uri = "http://82.223.27.144/dsWASMusic/ComprasLeerPorIDCompraGuid?IDCompraGuid=$id";
                  $ch = curl_init();
                  curl_setopt($ch, CURLOPT_URL, $uri);
                  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                  $result = curl_exec($ch);

                  curl_close($ch);
                  //$result = file_get_contents($uri);
                    // Will dump a beauty json :3
                  $object = json_decode($result, true);
                  $precio = $object['Precio'];
                  $idcompra = $object['IDCompra'];
                  // var_dump($object);
                ?>

                <div id="page-contents">
                <div class="container">
                <div class="row ">
                <div  class="col-md-12 post-content ">
                <div class="row pt-5 text-center">
                    <div class="col-2"></div>
                    <div class="col-8"><h3> Confirmar compra y pagar en pasarela de pago segura</h3></div>
                    <div class="col-2"></div>
                    <div class="col-12">
                         <p>Vas a realizar un pago de:</p>
                    </div>
                    <div class="col-12">
                         <center><h1 style="color:RED"><?php echo $precio . "€"?></h1></center>
                    </div>
                    <div class="col-12">
                         <center><h6>Factura Nº: <?php echo $id?></h6></center>
                    </div>

                </div>






                <?php } else { ?>

                <?php
                }?>
               <!-- PASARELA DE PAGO -->
                <?php
                if (true) {
                    include "tpv/apiRedsys.php";
                    $miObj = new RedsysAPI;
                    $url_tpv = 'https://sis.redsys.es/sis/realizarPago'; // PASARELA DE PRUEBAS
                    //$url_tpv = 'https://sis.redsys.es/sis/realizarPago'; // PASARELA DE PRODUCCIÓN
                    $version = "HMAC_SHA256_V1";
                    $clave = 'midps8Zl4zYrt9+0dusC14ZjnTVMxX2z'; //poner la clave SHA-256 facilitada por el banco
                    $name = 'MUSICIEN';
                    $code = '344615059';
                    $terminal='01';
                    $newid = str_pad($idcompra, 5, '0', STR_PAD_LEFT);
                    $order="$newid";
                    //var_dump($newid);
                    //$order="00011";
                    $totalpedido=$precio;
                    $amount=$totalpedido*100;
                    $currency = '978';
                    $consumerlng = '001';
                    $transactionType = '0';
                    $urlMerchant = 'http://www.musicien.es'; // URL DEL COMERCIO CMS
                    $urlweb_ok = 'http://www.musicien.es/ok.php'; // URL OK
                    $urlweb_ko = 'http://www.musicien.es/no-ok.php'; // URL NOK
                    $concepto = 'Compra Musicien';
                    $miObj->setParameter("DS_MERCHANT_AMOUNT",$amount);
                    $miObj->setParameter("DS_MERCHANT_CURRENCY",$currency);
                    $miObj->setParameter("DS_MERCHANT_ORDER",$order);
                    $miObj->setParameter("DS_MERCHANT_MERCHANTCODE",$code);
                    $miObj->setParameter("DS_MERCHANT_TERMINAL",$terminal);
                    $miObj->setParameter("DS_MERCHANT_TRANSACTIONTYPE",$transactionType);
                    $miObj->setParameter("DS_MERCHANT_MERCHANTURL",$urlMerchant);
                    $miObj->setParameter("DS_MERCHANT_URLOK",$urlweb_ok);
                    $miObj->setParameter("DS_MERCHANT_URLKO",$urlweb_ko);
                    $miObj->setParameter("DS_MERCHANT_MERCHANTNAME",$name);
                    $miObj->setParameter("DS_MERCHANT_CONSUMERLANGUAGE",$consumerlng);
                    $miObj->setParameter("DS_MERCHANT_PRODUCTDESCRIPTION",$concepto);
                    $miObj->setParameter("DS_MERCHANT_IDENTIFIER",'REQUIRED');



                    $params = $miObj->createMerchantParameters();
                    $signature = $miObj->createMerchantSignature($clave);

                ?>
                  <div class="container">
                    <div class="row p-5">

                        <div class="col-12 text-center">
                          <form id="realizarPago" action="<?php echo $url_tpv; ?>" method="post" target="_self">
                          <input type='hidden' name='Ds_SignatureVersion' value='<?php echo $version; ?>'>
                          <input type='hidden' name='Ds_MerchantParameters' value='<?php echo $params; ?>'>
                          <input type='hidden' name='Ds_Signature' value='<?php echo $signature; ?>'>
                          <button class="btn  btn-primary btn-block btn-sm mx-auto" type="submit" name="submitPayment" value="" / style="width: 300px;">
                            <i class="fa fa-lock" aria-hidden="true"></i>  PAGO SEGURO CON TARJETA
                        </button>
                          </form>

                        </div>

                          <div class="col-12 mt-5">
                   <img src="img/logo_p.png" class="m-0 p-0 d-block mx-auto" height="30"> <span class="ml-1">volver a <a href="http://www.musicien.es/#!/"> MUSICIEN</a> </span>

              </div>


                      </div>
                    </div>
                      </div>
                    </div>
                  </div>
                </div>



                <?php } else { ?>
                    <form class="form-amount" action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">
                    <div class="form-group">
                        <label for="tipodepago">Tipo de Pago</label>
                        <select id="tipodepago" name='tipodepago' class="form-control input-sm">
                            <option value="">SELECCIONA TIPO DE INGRESO</option>
                            <option value="-R">RESERVA DE VIAJE (200€)</option>
                            <option value="-C">PAGO COMPLETO DEL VIAJE</option>
                            <option value="-U">ÚLTIMO PAGO</option>
                        </select><br/>

                        <label for="amount">Cantidad</label>
                        <input type="text" id="cantidad" name="cantidad" autocomplete="off" class="form-control" placeholder="Por ejemplo: 450">
                        <label for="amount">Nº Factura <span style="color:red;font-style:italic">(no el nº de reserva)</span></label>
                        <input type="text" id="factura" name="factura" autocomplete="off" maxlength="12" class="form-control" placeholder="Por ejemplo: 000000923 (todos los números)">
                        <label for="amount">Concepto</label>
                        <input type="text" id="concepto" name="concepto" autocomplete="off" maxlength="125" class="form-control" placeholder="Por ejemplo: Manuel Gonzalez Perez - Viaje Valthorens 2016">
                    </div>
                    <input class="btn btn-lg btn-primary btn-block" name="submitPayment" type="submit" value="IR AL PASO 2">
                    </form>

                <?php }?>




    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.3/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script src="js/jquery.scrollbar.min.js"></script>
    <script src="js/script.js"></script>

    <!--Cosas DevExpress -->
    <script type="text/javascript" src="js/dx.all.js">

    </script>
    <link rel="stylesheet" href="css/dx.common.css">
    <link rel="stylesheet" href="css/dx.contrast.css">
    <link rel="stylesheet" href="css/dx.light.css">


<!-- COSAS DEL HOME -->
  <!-- <script src="js/jquery.min.js" ></script> -->
 <!--  <script src="js/bootstrap.min.js"></script> -->
  <script src="js/scrollPosStyler.js"></script>
  <script src="js/swiper.min.js"></script>
  <script src="js/isotope.min.js"></script>
  <script src="js/nivo-lightbox.min.js"></script>
  <script src="js/wow.min.js"></script>
  <script src="js/core.js"></script>


  </body>
</html>
